name: Update README

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

permissions:
  contents: write  # ðŸ”¥ Esto es clave para poder hacer commit y push
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v4.2.2
      
      - uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
